GET http://localhost:3001/api/posts

####################################

POST http://localhost:3001/api/create
Content-Type: application/json

{
  "title": "5EME MANCHE",
  "text": "lkjhfsqhefjn<lejksnf<jknfl<nflnlke",
  "username": "dosrider"
}

##################################
PUT http://localhost:3001/api/update
Content-Type: application/json

{
  "id": 3,
  "title": "nouveau post",
  "text": "J'ai reussi le post",
  "username": "dosrider"
}

####################################
DELETE http://localhost:3001/api/delete/1